---
development:
  auth_url: AS_SERVER_URL_TO_AUTHENTICATE_USER_GOES_HERE
  password: AS_USER_PASSWORD_GOES_HERE
  repositories_url: AS_SERVER_URL_TO_RETRIEVE_AS_EAD_GOES_HERE
test:
  auth_url: AS_SERVER_URL_TO_AUTHENTICATE_USER_GOES_HERE
  password: AS_USER_PASSWORD_GOES_HERE
  repositories_url: AS_SERVER_URL_TO_RETRIEVE_AS_EAD_GOES_HERE
production:
  auth_url: AS_SERVER_URL_TO_AUTHENTICATE_USER_GOES_HERE
  password: AS_USER_PASSWORD_GOES_HERE
  repositories_url: AS_SERVER_URL_TO_RETRIEVE_AS_EAD_GOES_HERE
