sample_development:
  aeon_url: 'AEON_HOST_GOES_HERE'
  shib_dll_url: 'REDIRECT_URL_GOES_HERE_FOR_SHIB_LOGIN'
  non_shib_dll_url: 'REDIRECT_URL_GOES_HERE_FOR_NON_SHIB_LOGIN'
  # if allow_requests is set to false, the form used to confirm and
  # enter details about the request, such as a note and/or a scheduled
  # date, will not be displayed.
  allow_requests: true
  # if display_request_notice is set to true, a notice will be displayed above
  # the form used to confirm the request. If the form is not displayed because
  # allow_requests is set to false, this notice can be used to give an
  # explanation and/or instructions. The header and text of the notice are
  # specified in header_notice_submit_request and text_notice_submit_request
  # in config/locales/aeon.en.yml which is under source control
  display_request_notice: false
sample_prod:
  aeon_url: 'AEON_HOST_GOES_HERE'
  shib_dll_url: 'REDIRECT_URL_GOES_HERE_FOR_SHIB_LOGIN'
  non_shib_dll_url: 'REDIRECT_URL_GOES_HERE_FOR_NON_SHIB_LOGIN'
  # if allow_requests is set to false, the form used to confirm and
  # enter details about the request, such as a note and/or a scheduled
  # date, will not be displayed.
  allow_requests: true
  # if display_request_notice is set to true, a notice will be displayed above
  # the form used to confirm the request. If the form is not displayed because
  # allow_requests is set to false, this notice can be used to give an
  # explanation and/or instructions. The header and text of the notice are
  # specified in header_notice_submit_request and text_notice_submit_request
  # in config/locales/aeon.en.yml which is under source control
  display_request_notice: false
