sample_development:
  # The auth_url is user dependent. For example:
  # 'https://as.example.com/api/users/USER_NAME/login'
  auth_url: 'AS_SERVER_URL_TO_AUTHENTICATE_USER_GOES_HERE'
  password: 'AS_USER_PASSWORD_GOES_HERE'
  repositories_url: 'AS_SERVER_URL_TO_RETRIEVE_AS_EAD_GOES_HERE'
  get_resource_params: 'resolve[]=linked_agents&resolve[]=subjects'
sample_prod:
  # The auth_url is user dependent. For example:
  # 'https://as.example.com/api/users/USER_NAME/login'
  auth_url: 'AS_SERVER_URL_TO_AUTHENTICATE_USER_GOES_HERE'
  password: 'AS_USER_PASSWORD_GOES_HERE'
  repositories_url: 'AS_SERVER_URL_TO_RETRIEVE_AS_EAD_GOES_HERE'
  get_resource_params: 'resolve[]=linked_agents&resolve[]=subjects'
