development: &DEV
  web_analytics: false
  # NOTE on authenticity_token_placeholder below: No need to change this string, the
  # code will automatically replace the string below with the authentication token
  # for the specific session
  authenticity_token_placeholder: '!!CUL_REPLACE_THIS_STRING_WITH_AUTHENTICITY_TOKEN!!'
  ead_cache_dir: <%= Rails.root.join('test/fixtures/files/ead') %>
  html_cache_dir: tmp/html_cache
  clio_redirect_url: 'https://clio.columbia.edu/catalog/'
  # Following string is used as a separator when "encoding" the list of requested containers
  # No need to change the given string.
  container_info_delimiter: 'CONTAINERINFODELIMITER'
  lweb_help_url: https://library.columbia.edu/collections.html
  # During development/testing, the AS server may not be accessible. In this case, the code
  # should not attempt to authenticate on the AS server. To bypass authentication, set
  # the following to true. On the production server, it should be set to false since
  # authentication is required to access the AS server API.
  bypass_as_authentication: true
  # log_bib_id_repo_id_hash_cache_expiration is set to true to turn on expiration
  # of the cache contaning the info from file of valid bib IDs and associated
  # repo codes.
  log_bib_id_repo_id_hash_cache_expiration: true
  # bib_id_repo_id_hash_cache_expiration_in_hours indicates when to expire
  # the cache contaning the info from file of valid bib IDs and associated
  # repo codes.
  bib_id_repo_id_hash_cache_expiration_in_hours: 12
  cache_html: false
  mirador_base_url: https://dlc-staging.library.columbia.edu
  embedding_service_base_url: http://localhost:9292
  #search mode options are 'standard' or 'vector'
  default_search_mode: 'standard'
test:
  <<: *DEV
  ead_cache_dir: <%= Rails.root.join('test/fixtures/files/ead') %>
  html_cache_dir: tmp/html_cache
production:
  web_analytics: true
  # NOTE on authenticity_token_placeholder below: No need to change this string, the
  # code will automatically replace the string below with the authentication token
  # for the specific session
  authenticity_token_placeholder: '!!CUL_REPLACE_THIS_STRING_WITH_AUTHENTICITY_TOKEN!!'
  ead_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_EADS_WILL_BE_STORED'
  html_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_HTML_PAGES_WILL_BE_STORED'
  clio_redirect_url: 'https://clio.columbia.edu/catalog/'
  # Following string is used as a separator when "encoding" the list of requested containers
  # No need to change the given string.
  container_info_delimiter: 'CONTAINERINFODELIMITER'
  lweb_help_url: https://library.columbia.edu/collections.html
  mirador_base_url: https://dlc.library.columbia.edu
  embedding_service_base_url: http://localhost:9292
