sample_development:
  use_fixtures: true
  google_analytics: false
  # NOTE on authenticity_token_placeholder below: No need to change this string, the
  # code will automatically replace the string below with the authentication token
  # for the specific session
  authenticity_token_placeholder: '!!CUL_REPLACE_THIS_STRING_WITH_AUTHENTICITY_TOKEN!!'
  ead_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_EADS_WILL_BE_STORED'
  html_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_HTML_PAGES_WILL_BE_STORED'
  clio_bib_id_data_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_CONTAINING_CLIO_BIB_ID_DATA'
  clio_redirect_url: 'https://clio.columbia.edu/catalog/'
  # Following string is used as a separator when "encoding" the list of requested containers
  # No need to change the given string.
  container_info_delimiter: 'CONTAINERINFODELIMITER'
  fa_lists_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_CONTAINING_LISTS_OF_FINDING_AIDS'
sample_prod:
  use_fixtures: false
  google_analytics: true
  # NOTE on authenticity_token_placeholder below: No need to change this string, the
  # code will automatically replace the string below with the authentication token
  # for the specific session
  authenticity_token_placeholder: '!!CUL_REPLACE_THIS_STRING_WITH_AUTHENTICITY_TOKEN!!'
  ead_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_EADS_WILL_BE_STORED'
  html_cache_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_WHERE_CACHED_HTML_PAGES_WILL_BE_STORED'
  clio_bib_id_data_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_CONTAINING_CLIO_BIB_ID_DATA'
  clio_redirect_url: 'https://clio.columbia.edu/catalog/'
  # Following string is used as a separator when "encoding" the list of requested containers
  # No need to change the given string.
  container_info_delimiter: 'CONTAINERINFODELIMITER'
  fa_lists_dir: 'ABSOLUTE_PATH_TO_DIRECTORY_CONTAINING_LISTS_OF_FINDING_AIDS'
