base: &BASE
  nnc:
    # Add a request type to display a request button
    request_types:
      # Display the aeon request button, which will allow the user to add an item to their cart
      aeon_local_request:
        # The Aeon site code that identifies this repository.  This value is
        # supplied to the Aeon 'Site' field during an Aeon submission.
        site_code: PLACEHOLDERSITECODE
        # When user_review is set to true, this will result in an Aeon submission with a
        # UserReview parameter value of "Yes".  This will cause the submision to be routed to
        # the Aeon "Awaiting User Review" queue, and the user will need to approve it in the
        # Aeon UI before it moves to any other queue.  If this value is set to false,
        # this will result in an Aeon submission with a UserReview parameter value of "No".
        user_review: true
    name: Columbia University Libraries
    # exclude_from_home indicates whether a repository should be displayed on the homepage
    exclude_from_home: true
    contact:
      phone: 212-854-7309
      email: lio@columbia.edu
    location:
      link:
        url: https://library.columbia.edu
        label: Columbia University Libraries Home Page
      street_address:
        address: ['535 West 114th St.']
        city_state_zip_country: New York, NY 10027, USA
    description: Columbia University Libraries is a top-tier academic research library, serving one of the world's most important centers of research and learning.
    thumbnail_url: https://library.columbia.edu/content/dam/locations/butler.jpg
    icon: light fa-landmark-flag
  nnc-a:
    request_types:
      aeon_local_request:
        site_code: AVERYDACUL
        user_review: true
    name: Avery Drawings & Archives Collections
    exclude_from_home: false
    contact:
      email: avery@library.columbia.edu
    location:
      link:
        url: http://library.columbia.edu/locations/avery.html
        label: Avery Home Page
      street_address:
        building: 300 Avery Hall
        address: ["1172 Amsterdam Ave."]
        city_state_zip_country: New York, NY 10027, USA
    description: Avery is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_avery.png
    icon: light fa-compass-drafting
  nnc-ccoh:
    request_types:
      aeon_local_request:
        site_code: RBMLCUL
        user_review: true
    name: Oral History Archives at Columbia
    exclude_from_home: false
    contact:
      email: oralhist@library.columbia.edu
    location:
      link:
        url: https://library.columbia.edu/libraries/ccoh/FAQ.html
        label: OHAC Home Page
      street_address:
        building: 6th Floor East Butler Library
        address: ['535 West 114th Street']
        city_state_zip_country: New York, NY 10027, USA
    description: OHAC is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_ccoh.png
    icon: light fa-microphone-lines
  nnc-ea:
    request_types:
      aeon_local_request:
        site_code: STARRCUL
        user_review: true
    name: C.V. Starr East Asian Library
    url: https://findingaids.library.columbia.edu/ead/nnc-ea
    exclude_from_home: false
    contact:
      email: starr@library.columbia.edu
    location:
      link:
        url: http://library.columbia.edu/locations/eastasian.html
        label: C.V. Starr Home Page
      street_address:
        building: 300 Kent Hall
        address: ['1140 Amsterdam Ave.']
        city_state_zip_country: New York, NY 10027, USA
    description: CV Starr is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_eastasian.png
    icon: light fa-earth-asia
  nnc-rb:
    request_types:
      aeon_local_request:
        site_code: RBMLCUL
        user_review: true
    name: Rare Book & Manuscript Library
    exclude_from_home: false
    contact:
      email: rbml@library.columbia.edu
    location:
      link:
        url: http://library.columbia.edu/locations/rbml.html
        label: RBML Home Page
      street_address:
        building: 6th Floor East Butler Library
        address: ['535 West 114th Street']
        city_state_zip_country: New York, NY 10027, USA
    description: RBML is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_rbml.png
    icon: light fa-book-sparkles
  nnc-ua:
    request_types:
      aeon_local_request:
        site_code: RBMLCUL
        user_review: true
    name: Columbia University Archives
    exclude_from_home: false
    contact:
      email: uarchives@columbia.edu
    location:
      link:
        url: http://library.columbia.edu/locations/cuarchives.html
        label: University Archives Home Page
      street_address:
        building: 6th Floor East Butler Library
        address: ['535 West 114th Street']
        city_state_zip_country: New York, NY 10027, USA
    description: University Archives is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_cuarchives.png
    icon: light fa-box-archive
  nnc-ut:
    request_types:
      aeon_local_request:
        site_code: BURKECUL
        user_review: true
    name: Burke Library at Union Theological Seminary
    exclude_from_home: false
    contact:
      email: burke@library.columbia.edu
    location:
      link:
        url: http://library.columbia.edu/locations/burke.html
        label: Burke Home Page
        street_address:
          building: Union Theological Seminary
          address: ['3041 Broadway']
        city_state_zip_country: New York, NY 10027, USA
    description: Burke is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_burke.png
    icon: light fa-scroll-old
  nnc-m:
    name: Health Sciences Library
    exclude_from_home: true
    contact:
      email: hsl@example.org
    location:
      link:
        url: https://www.library-archives.cumc.columbia.edu/
        label: HSL Home Page
      street_address:
        building: Hammer Health Sciences Building, Room LL1-111
        address:
          - Columbia University Medical Center
          - 701 West 168th Street
        city_state_zip_country: New York, NY 10032, USA
    description: HSL is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_burke.png
    icon: light fa-stethoscope
  nynycoh:
    name: Oral History Archives at Columbia
    exclude_from_home: true
    contact:
      email: oralhist@library.columbia.edu
    location:
      link:
        url: https://library.columbia.edu/libraries/ccoh/FAQ.html
        label: OHAC Home Page
      street_address:
        building: 6th Floor East Butler Library
        address: ['535 West 114th Street']
        city_state_zip_country: New York, NY 10027, USA
    description: OHAC is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/templates/libraryweb/banners/banner_ccoh.png
    icon: light fa-microphone-lines
  nynybaw:
    name: Barnard Archives & Special Collections
    exclude_from_home: false
    contact:
      email: archives@barnard.edu
    location:
      link:
        url: https://archives.barnard.edu/
        label: Barnard Archives & Special Collections
      street_address:
        building: Milstein Center for Teaching and Learning 423
        address:
        - Barnard College
        - 3009 Broadway
        city_state_zip_country: New York, NY 10027, USA
    description: Barnard is a wonderful repository
    thumbnail_url: https://library.columbia.edu/content/dam/locations/barnard-archives.jpg
    icon: light fa-wreath-laurel
development:
  <<: *BASE
test:
  <<: *BASE
production:
  <<: *BASE
