sample_prod_based_on_20Aug21_copy:
  nnc-a:
    # requestable_via_aeon is set to true to enable aeon requests for a repo
    requestable_via_aeon: true
    # in the original implementation for RBML, a checkbox was created only at
    # the container level. So if a few consecutive items were in the same
    # container (for example, Box 1), there was only one checkbox for the
    # container as a whole for that set of items. This is the behavior if
    # requestable_via_aeon is set to false
    # requestable_via_aeon is set to true to make each item selectable
    # individually, which was a feature requested by Avery.
    checkbox_per_unittitle: true
    # aeon_site_code is used by the aeon server to identify the repo
    aeon_site_code: AVERYDACUL
    # as_repo_id indicates the ID used to identify the repo on the archivespace
    # server. Note that some repos share the same ID
    as_repo_id: 3
    name: Avery Drawings & Archives Collections
    # url is the desired url to be used for the library link at the top of a
    # finding aids page
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-a
    # view_style indicates which series view to use. This is a legacy setting;
    # Avery had a different styling (style_a) then the other repos (style_b).
    # However, when aeon requests were added to Avery finding aids, Avery was
    # also moved to style_b
    view_style: style_b
    # has_fa_list indicates whether or not a repo has an entry in the 
    # home/main/landingpage for the findingaids app
    has_fa_list: true

  nnc-ccoh:
    requestable_via_aeon: true
    checkbox_per_unittitle: false
    aeon_site_code: RBMLCUL
    as_repo_id: 2
    name: 'Oral History Archives at Columbia'
    url: https://library.columbia.edu/locations/ccoh.html
    view_style: style_b
    has_fa_list: true

  nnc-ea:
    requestable_via_aeon: true
    checkbox_per_unittitle: false
    aeon_site_code: STARRCUL
    as_repo_id: 4
    name: C.V. Starr East Asian Library
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-ea
    view_style: style_b
    has_fa_list: true

  nnc-rb:
    requestable_via_aeon: true
    checkbox_per_unittitle: false
    aeon_site_code: RBMLCUL
    as_repo_id: 2
    name: Rare Book & Manuscript Library
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-rb
    view_style: style_b
    has_fa_list: true

  nnc-ua:
    requestable_via_aeon: true
    checkbox_per_unittitle: false
    aeon_site_code: RBMLCUL
    as_repo_id: 2
    name: Columbia University Archives
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-ua
    view_style: style_b
    has_fa_list: true

  nnc-ut:
    requestable_via_aeon: true
    checkbox_per_unittitle: false
    aeon_site_code: BURKECUL
    as_repo_id: 5
    name: 'Burke Library at Union Theological Seminary'
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-ut
    view_style: style_b
    has_fa_list: true

  nnc-m:
    requestable_via_aeon: false
    as_repo_id: 'clio_only'
    name: 'Health Sciences Library'
    url: http://archivesportal.library.columbia.edu/repository.php?r=nnc-m
    view_style: style_b
    has_fa_list: false

  nynycoh:
    requestable_via_aeon: false
    as_repo_id: 'clio_only'
    name: 'Oral History Archives at Columbia'
    url: https://library.columbia.edu/locations/ccoh.html
    view_style: style_b
    has_fa_list: false
