name: CI

on:
  push:
    branches: 
      - '**'

jobs:
  ci-rails-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.3']
        node: ['20']
    env:
      RAILS_ENV: test
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      # - uses: actions/checkout@v3
      # - name: Install libxslt for nokogiri gem (required for version < 1.11)
      #   run: sudo apt-get install -y libxml2-dev libxslt-dev
      # - name: Add --no-document option to .gemrc file to speed up bundle install
      #   run: "echo 'gem: --no-document' > ~/.gemrc"
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ matrix.ruby-version }}
      #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # - name: Set up Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node }}
      - name: Set up .npmrc
        run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{secrets.TEST_SECRET}}" > .npmrc
      - name: Display .npmrc info
        run: cat .npmrc
      # - run: npm install -g yarn
      # - run: yarn install
      # - run: yarn run lint
      # - name: Run setup task
      #   run: bundle exec rake acfa:setup:all
      # - name: Run CI task
      #   run: bundle exec rspec
